### ISSUE TITLE
Including translated names in NameToAlpha2

### ISSUE THREAD

**Issue by oschwald** [pariz/gountries#14]
Would you be willing to accept a PR that adds translated country names to `NameToAlpha2`? I've run into several cases where lookups by name have failed but the spelling variant is among the translations.

**Comment by pariz** [comment]
Can you elaborate a bit on a case where this would be applicable?

**Comment by oschwald** [comment]
We receive country names from our customers and some times these are in another language (e.g., Spanish or Russian). Generally, `gountries` already has the name in the data files, but not in the `NameToAlpha2` map, which only contains the common name and the official name.

**Comment by pariz** [comment]
Hi again. If this is still relevant to you, please post a PR! 👍
