### ISSUE TITLE
List all countries

### ISSUE THREAD

**Issue by nd2s** [pariz/gountries#15]
Isn't there a way of getting a list of all countries?

**Comment by pariz** [comment]
Hi, @nd2s.
There is.
```
query := gountries.New()

gountries.Countries // is a map[string]Country{}
```

However, i think i should add this as a struct method on `Query` because it feels it makes more sense.
Something along the lines of `query.FindAllCountries()` which returns the same `map[string]Country{}`

I'll tag a new version this fix soon

**Comment by nd2s** [comment]
Thanks!
