### ISSUE TITLE
Issues with data directory

### ISSUE THREAD

**Issue by pyeremenko** [pariz/gountries#2]
I faced with 2 issues

* `go get` doesn't fetch content of `data` directory so it's empty after obtaining a project
* example code fails with panic `panic: Error loading Countries` because it expects current directory of executable to contain `data` directory. But it's actually not there but inside `github.com/pariz/gountries`

**Comment by pariz** [comment]
Hi,
It seems go get isn't capable of fetching submodules.
I've included a raw copy of the countries repo into the data directory now, which will do at the moment.
This should probably be fixed with a build script later on.

**Comment by Komosa** [comment]
Maybe `git submodule update --init --recursive` (knowledge taken from: https://github.com/dpw/vendetta)?

**Comment by pariz** [comment]
I was thinking along those lines. Another way is to include the language files as a vendor package. I'll give it some thought :) Thanks for the feedback
