### ISSUE TITLE
Unicode symbols or \u codes?

### ISSUE THREAD

**Issue by ArtemT** [pariz/gountries#3]
Hello and thanks for sharing.

I noticed that your data contains unicode symbols in `data/json/countries/` while `\u<number>` form is used in `countries.json`. Has it been done intentionally?

Is it possible to use plain unicode in `countries.json` too? I believe it's better for readability and grammar checking.

**Comment by pariz** [comment]
Hello,

countries.json is deprecated in gountries but is used in the generator that creates the country data ([gountries-creator](https://github.com/pariz/gountries-creator)). You can find it here: `https://github.com/pariz/gountries-creator/blob/master/src/countries.json`

The proper output should be pure unicode characters, as found in the generated `.yaml` and `.json` files. :)
I'm currently reworking the generation of the json files, btw. Give it a couple of days and there will be better structured data there. As of now is kind of experimental.

Any further questions regarding the data source should be made to `gountries-creator`. If you feel like helping, you can fork the generator and patch it yourself. The generator code, however, isn't exactly pretty. Quite hacky at the moment. But it works. I guess i'll make a rewrite of it whenever possible.
